apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canary
  name: canary-v1
  namespace: udacity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
        version: "1.0"
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: configmap-vol
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: configmap-vol
          configMap:
            name: canary-config-v1